### ISSUE TITLE
sqlite3.OperationalError

### ISSUE THREAD

**Issue by Michael-E-Rose** [ushahidi/geograpy#25]
Fresh install on Python3 on Ubuntu 16.04

```
import geograpy
address = geograpy.get_place_context(text='United States')
```
results in 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/geograpy/__init__.py", line 9, in get_place_context
    pc = PlaceContext(e.places)
  File "/usr/local/lib/python3.5/dist-packages/geograpy/places.py", line 17, in __init__
    self.conn = sqlite3.connect(db_file)
sqlite3.OperationalError: unable to open database file
```

**Comment by naspuka** [comment]
plz I am also having this error

Traceback (most recent call last):
  File "sm.py", line 36, in <module>
    pc = places.PlaceContext(['Cleveland', 'Ohio', 'United States'])
  File "/usr/local/lib/python3.6/dist-packages/geograpy3/places.py", line 34, in __init__
    self.conn = sqlite3.connect(db_file)
sqlite3.OperationalError: unable to open database file

**Comment by jamiebull1** [comment]
This is unmaintained. Try here https://github.com/Corollarium/geograpy2

**Comment by QLgogo** [comment]
Hi, I have similar issue. When run "geograpy.get_place_context(text=text)" after "import geograpy", I got error "sqlite3.OperationalError: database is locked". Then I turn to geograpy2. 
But I got issue when installing geograpy2 by "pip install --user geograpy2". The error is "ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output." Anyone can help? Thanks a lot!
