### ISSUE TITLE
OperationalError: unable to open database file

### ISSUE THREAD

**Issue by naspuka** [ushahidi/geograpy#33]
plz I am having a big error here
Traceback (most recent call last):
  File "sm.py", line 36, in <module>
    pc = places.PlaceContext(['Cleveland', 'Ohio', 'United States'])
  File "/usr/local/lib/python3.6/dist-packages/geograpy3/places.py", line 34, in __init__
    self.conn = sqlite3.connect(db_file)
sqlite3.OperationalError: unable to open database file

**Comment by jamiebull1** [comment]
https://github.com/Corollarium/geograpy2

**Comment by WolfgangFahl** [comment]
you might want to use the more recent https://github.com/somnathrakshit/geograpy3
