### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'name'

### ISSUE THREAD

**Issue by cusco** [ushahidi/geograpy#35]
>>> p = geograpy.get_place_context(text='Pristina')                                                                 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cusco/VirtualEnvs/data_parser/lib/python3.7/site-packages/geograpy/__init__.py", line 12, in get_place_context
    pc.set_cities()
  File "/home/cusco/VirtualEnvs/data_parser/lib/python3.7/site-packages/geograpy/places.py", line 160, in set_cities
    country_name = country.name
AttributeError: 'NoneType' object has no attribute 'name'

'NoneType' object has no attribute 'name'

**Comment by jamiebull1** [comment]
https://github.com/Corollarium/geograpy2

**Comment by cusco** [comment]
> https://github.com/Corollarium/geograpy2

Is this a fork?

**Comment by jamiebull1** [comment]
From the README:

>A rewrite that fixes more issues is available here, please use it instead: https://github.com/Corollarium/geograpy2

**Comment by jamiebull1** [comment]
> From the README:
> 
> > A rewrite that fixes more issues is available here, please use it instead: https://github.com/Corollarium/geograpy2

Although it's also unmaintained since 2015...

**Comment by cusco** [comment]
> > From the README:
> > > A rewrite that fixes more issues is available here, please use it instead: https://github.com/Corollarium/geograpy2
> 
> Although it's also unmaintained since 2015...

Right..! 
Thank you

**Comment by jamiebull1** [comment]
@cusco there are a *lot* of forks of this package. Maybe you can find one that's in a better state.

**Comment by cusco** [comment]
> @cusco there are a _lot_ of forks of this package. Maybe you can find one that's in a better state.

Is there a particular one that you would suggest @jamiebull1 ?

**Comment by jamiebull1** [comment]
@cusco afraid not. I don't have a use for this toola t the moment

**Comment by WolfgangFahl** [comment]
you might want to use the more recent https://github.com/somnathrakshit/geograpy3
