### ISSUE TITLE
Cannot install it in Python3

### ISSUE THREAD

**Issue by spartakos87a** [ushahidi/geograpy#4]
When I try to install to Python3 many errors come up...is there any solution??

**Comment by HEHenson** [comment]
I am in the same boat

**Comment by shun-liang** [comment]
I have the same problem. When trying to run geograpy-nltk, I get the following error:

```
Traceback (most recent call last):
  File "/Users/shun/.virtualenvs/hn_hiring_trend/bin/geograpy-nltk", line 5, in <module>
    nltk.downloader('maxent_ne_chunker')
TypeError: 'module' object is not callable
```

**Comment by shun-liang** [comment]
And error when trying to import geograpy:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/shun/.virtualenvs/hn_hiring_trend/lib/python3.5/site-packages/geograpy/__init__.py", line 1, in <module>
    from extraction import Extractor
ImportError: No module named 'extraction'
```

**Comment by jamiebull1** [comment]
+1

**Comment by Ireneruru** [comment]
In the same boat；、

**Comment by yuriy-fineway** [comment]
I got the same problem, but I have 2 errors

1. `Command "python setup.py egg_info" failed with error code 1`
2. `WARNING! You are attempting to install newspaper's python2 repository on python3. PLEASE RUN $ pip3 install newspaper3k for python3 or $ pip install newspaper for python2`. This one occurs, even though newspaper is installed

**Comment by RahulKumarSavariya** [comment]
any solution related above error ?

**Comment by RahulKumarSavariya** [comment]
You can install with this command line 
python3 -m pip install git+https://github.com/reach2ashish/geograpy.git

if you working on conda virtual environment then 
python -m pip install git+https://github.com/reach2ashish/geograpy.git

for whole document : https://github.com/ushahidi/geograpy/issues/21

**Comment by nilani-rangika** [comment]
install geograpy3 for python3

https://pypi.org/project/geograpy3/

**Comment by mlkshclk** [comment]
@RahulKumarSavariya's [suggestion ](https://github.com/ushahidi/geograpy/issues/4#issuecomment-559794270)worked for me:

> You can install with this command line
> python3 -m pip install git+https://github.com/reach2ashish/geograpy.git
> 
> if you working on conda virtual environment then
> python -m pip install git+https://github.com/reach2ashish/geograpy.git
> 
> for whole document : #21

**Comment by WolfgangFahl** [comment]
you might want to use the more recent https://github.com/somnathrakshit/geograpy3
