### ISSUE TITLE
ImportError: No module named 'extraction'

### ISSUE THREAD

**Issue by acquayefrank** [ushahidi/geograpy#9]
Hi, 
I just came across this library and was trying it out but  every time I try to....

import geograpy

I get this error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Larry/miniconda3/envs/fido/lib/python3.5/site-packages/geograpy/__init__.py", line 1, in <module>
    from extraction import Extractor
ImportError: No module named 'extraction'

**Comment by acquayefrank** [comment]
Apparently the library depends on ....  https://pypi.python.org/pypi/extraction/   I think it should be added as a dependency

**Comment by acquayefrank** [comment]
I just realised it does not depend on https://pypi.python.org/pypi/extraction/  ... but rather it's not compatible with python3 hence it's an import issue

**Comment by tomtom92** [comment]
Has this been fixed? If I need to import this package, is there something that I can do to run it in Python2 so that it will load correctly?

**Comment by tekavw** [comment]
Any solution guys please ?

**Comment by tomtom92** [comment]
@tekavw last time I tried (several months ago), I wasn't able to get this to work, even after correcting the dependency. I would suggest looking at the [https://github.com/ushahidi/geograpy/issues/21](other issue involving Python3) and see if you can instead get this to work with Python3. Let me know how it goes.

**Comment by ChristianFrisson** [comment]
Pull request https://github.com/lethain/extraction/pull/5 solves your issue.

**Comment by WolfgangFahl** [comment]
you might want to use the more recent https://github.com/somnathrakshit/geograpy3
